; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://platformio.org

[env:esp32-c3-devkitm-1]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino
lib_deps = 
    h2zero/NimBLE-Arduino@^1.4.1
    mathertel/OneButton@^2.6.2
    t-vk/ESP32 BLE Keyboard@^0.3.2

build_unflags = -std=gnu++11 -std=gnu++14 -std=c++11 -std=c++14
build_flags = 
    -std=gnu++17 
    -D USE_NIMBLE
    ; Uncomment below if your board does not output Serial prints over USB
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1

monitor_speed = 115200

; Wireless OTA Upload Settings
upload_protocol = espota
upload_port = 192.168.1.200       ; Replace with your ESP32's IP address
upload_flags = 
    --auth=password                ; The password set in ArduinoOTA.setPassword()